name: Lint and test production branch

on:
  push:
    branches:
      - production

concurrency:
  group: ci-build_${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/cache-modules
        id: cache-modules
      - uses: ./.github/actions/install-dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/cache-modules
      - uses: ./.github/actions/lint-app

  unit-test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/cache-modules
      - uses: ./.github/actions/test-frontend
      - uses: ./.github/actions/test-backend

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/cache-modules
      - uses: ./.github/actions/cache-build
        id: cache-build
      - uses: ./.github/actions/build-app
        if: steps.cache-build.outputs.cache-hit != 'true'

  run-cypress-test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        spec:
          [
            "Account",
            "Expenses",
            "Incomes",
            "TransactionCategories",
            "Transfer",
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/cache-modules
      - uses: ./.github/actions/cache-build
      - uses: ./.github/actions/test-cypress
        with:
          cypress-spec-folder: ${{ matrix.spec }}

  build-docker:
    needs:
      - lint
      - unit-test
      - run-cypress-test
    uses: ./.github/workflows/build-docker.yml
    secrets:
      REGISTERY_TOKEN: ${{ secrets.REGISTERY_TOKEN }}
      DOCKER_TARGET_PLATFORMS: ${{ secrets.DOCKER_TARGET_PLATFORMS }}
